// import { ConnectButton } from "@rainbow-me/rainbowkit";
import { ConnectButton, ConnectEmbed } from "thirdweb/react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
// import { Swap } from "../components/Swap";
import { createThirdwebClient } from "thirdweb";
import { createWallet } from "thirdweb/wallets";
import { arbitrum, avalanche, base, bsc, mainnet, optimism, polygon, zora } from "thirdweb/chains";

console.log('arbitrum', arbitrum, mainnet, avalanche)

const sonic = {
  id: 146,
  name: "Sonic",
  nativeCurrency: {
    decimals: 18,
    name: "S",
    symbol: "S",
  },
  rpc: 'https://146.rpc.thirdweb.com',
  blockExplorers: [
    {
      name: "SonicScan",
      url: "https://sonicscan.org",
    }
  ],
}

const berachain = {
  id: 80094,
  name: "Berachain",
  nativeCurrency: {
    decimals: 18,
    name: "bera",
    symbol: "BERA",
  },
  rpc: 'https://80094.rpc.thirdweb.com',
  blockExplorers: [
    {
      name: "Berascan",
      url: "https://berascan.com",
    },
  ],
}

const chains = [mainnet, polygon, arbitrum, optimism, avalanche, sonic, zora, berachain];

const client = createThirdwebClient({
  clientId: "654d245030441fe158c45b853815aa08"
})

const wallets = [
  createWallet("io.metamask"),
  createWallet("com.coinbase.wallet"),
  createWallet("me.rainbow"),
  createWallet("io.rabby"),
  createWallet("io.zerion.wallet"),
  createWallet("com.bitget.web3"),
  createWallet("com.trustwallet.app"),
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Magic Swap</title>
        <meta
          content="Generated by magicfi"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className={styles.main}>
        <ConnectButton
          client={client}
          wallets={wallets}
          chains={chains}
          connectModal={{
            size: "wide",
            showThirdwebBranding: false,
          }}
        />       

        <h1 className={styles.title}>
          Marbin Swap
        </h1>

        {/* <Swap /> */}
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made by Magic Fi
        </a>
      </footer>
    </div>
  );
};

export default Home;
